SELECT * FROM EMPLOYEE;

SELECT FNAME, LNAME, SALARY, DNO FROM EMPLOYEE;

SELECT P.PNAME, P.PLOCATION, D.DNAME
FROM PROJECT P
JOIN DEPARTMENT D ON P.DNUM = D.DNUMBER;

SELECT FNAME + ' ' + LNAME AS FullName, (SALARY * 12 * 0.10) AS [ANNUAL COMM]
FROM EMPLOYEE;

SELECT SSN, FNAME + ' ' + LNAME AS FullName
FROM EMPLOYEE
WHERE SALARY > 1000;

SELECT SSN, FNAME + ' ' + LNAME AS FullName
FROM EMPLOYEE
WHERE SALARY * 12 > 10000;

SELECT FNAME, LNAME, SALARY
FROM EMPLOYEE
WHERE SEX = 'F';

SELECT DNUMBER, DNAME
FROM DEPARTMENT
WHERE MGRSSN = '968574';

SELECT PNUMBER, PNAME, PLOCATION
FROM PROJECT
WHERE DNUM = 10;